export const PROMETHEUS_COUNTER_SERVICE_DI = Symbol('PROMETHEUS_COUNTER_SERVICE_DI');
export const PROMETHEUS_GAUGE_SERVICE_DI = Symbol('PROMETHEUS_GAUGE_SERVICE_DI');
export const PROMETHEUS_HISTOGRAM_SERVICE_DI = Symbol('PROMETHEUS_HISTOGRAM_SERVICE_DI');
export const PROMETHEUS_SUMMARY_SERVICE_DI = Symbol('PROMETHEUS_SUMMARY_SERVICE_DI');
