export const REDIS_CACHE_MANAGER_REDIS_CLIENT_OPTIONS_DI = Symbol('REDIS_CACHE_MANAGER_REDIS_CLIENT_OPTIONS_DI');
export const REDIS_CACHE_MANAGER_KEYV_REDIS_OPTIONS_DI = Symbol('REDIS_CACHE_MANAGER_KEYV_REDIS_OPTIONS_DI');
export const REDIS_CACHE_MANAGER_REDIS_CLIENT_DI = Symbol('REDIS_CACHE_MANAGER_REDIS_CLIENT_DI');
