networks:
  dev-local:
    driver: bridge

volumes:
  postgres:
  redis:
  kafka:
  rabbitmq:

services: 
  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
    networks:
     - dev-local

  redis-ui:
    image: redis/redisinsight:latest
    container_name: redis-ui
    restart: always
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - dev-local

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: notification
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - dev-local
