export const HTTP_CLIENT_HEADERS_REQUEST_BUILDER_DI = Symbol('HTTP_CLIENT_HEADERS_REQUEST_BUILDER_DI');
export const HTTP_CLIENT_HTTP_MODULE_OPTIONS_DI = Symbol('HTTP_CLIENT_HTTP_MODULE_OPTIONS_DI');
export const HTTP_CLIENT_REQUEST_OPTIONS_DI = Symbol('HTTP_CLIENT_REQUEST_OPTIONS_DI');
